<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { AxiosError } from 'axios';
import { addProjectMember, listProjectMembers, removeProjectMember, type ProjectMember } from '../api/members-api';
import { getProject, type Project } from '../api/projects-api';
import { createTask, deleteTask, listTasks, updateTask, type Task, type TaskPayload, type TaskStatus } from '../api/tasks-api';
import MembersModal from '../components/MembersModal.vue';
import TaskCard from '../components/TaskCard.vue';
import TaskModal from '../components/TaskModal.vue';
import { useAuthStore } from '../stores/auth';

const props = defineProps<{ id: string }>();
const auth = useAuthStore();
const project = ref<Project | null>(null); const members = ref<ProjectMember[]>([]); const tasks = ref<Task[]>([]); const loading = ref(true); const error = ref(''); const taskError = ref(''); const memberError = ref(''); const savingTask = ref(false); const savingMember = ref(false); const showTask = ref(false); const showMembers = ref(false); const selectedTask = ref<Task | null>(null);
const columns: { status: TaskStatus; label: string }[] = [{ status: 'todo', label: 'Todo' }, { status: 'in_progress', label: 'In progress' }, { status: 'done', label: 'Done' }];
const groupedTasks = computed<Record<TaskStatus, Task[]>>(() => ({ todo: tasks.value.filter((task) => task.status === 'todo'), in_progress: tasks.value.filter((task) => task.status === 'in_progress'), done: tasks.value.filter((task) => task.status === 'done') }));
const projectId = computed(() => Number(props.id)); const canManageMembers = computed(() => project.value?.owner_id === auth.user?.id);
function displayError(exception: unknown, fallback: string): string { if (exception instanceof AxiosError && exception.response?.status === 422) return 'Please review the information and try again.'; if (exception instanceof AxiosError && exception.response?.status === 403) return 'You do not have permission for this action.'; return fallback; }
async function load(): Promise<void> { loading.value = true; error.value = ''; try { const [loadedProject, loadedMembers, loadedTasks] = await Promise.all([getProject(projectId.value), listProjectMembers(projectId.value), listTasks(projectId.value)]); project.value = loadedProject; members.value = loadedMembers; tasks.value = loadedTasks; } catch (exception) { error.value = displayError(exception, 'Unable to load this project.'); } finally { loading.value = false; } }
function openCreateTask(): void { selectedTask.value = null; taskError.value = ''; showTask.value = true; } function openTask(task: Task): void { selectedTask.value = task; taskError.value = ''; showTask.value = true; }
async function saveTask(payload: TaskPayload): Promise<void> { savingTask.value = true; taskError.value = ''; try { const result = selectedTask.value ? await updateTask(projectId.value, selectedTask.value.id, payload) : await createTask(projectId.value, payload); const index = tasks.value.findIndex((task) => task.id === result.id); if (index >= 0) tasks.value.splice(index, 1, result); else tasks.value.unshift(result); showTask.value = false; } catch (exception) { taskError.value = displayError(exception, 'Unable to save the task.'); } finally { savingTask.value = false; } }
async function removeTask(): Promise<void> { if (!selectedTask.value || !window.confirm(`Delete “${selectedTask.value.title}”?`)) return; savingTask.value = true; taskError.value = ''; try { await deleteTask(projectId.value, selectedTask.value.id); tasks.value = tasks.value.filter((task) => task.id !== selectedTask.value?.id); showTask.value = false; } catch (exception) { taskError.value = displayError(exception, 'Unable to delete the task.'); } finally { savingTask.value = false; } }
async function addMember(email: string): Promise<void> { savingMember.value = true; memberError.value = ''; try { members.value.push(await addProjectMember(projectId.value, email)); } catch (exception) { memberError.value = displayError(exception, 'Unable to add this member.'); } finally { savingMember.value = false; } }
async function removeMember(member: ProjectMember): Promise<void> { if (!window.confirm(`Remove ${member.name} from this project?`)) return; savingMember.value = true; memberError.value = ''; try { await removeProjectMember(projectId.value, member.id); members.value = members.value.filter((item) => item.id !== member.id); tasks.value = tasks.value.map((task) => task.assigned_to === member.id ? { ...task, assigned_to: null } : task); } catch (exception) { memberError.value = displayError(exception, 'Unable to remove this member.'); } finally { savingMember.value = false; } }
onMounted(load);
</script>

<template>
    <section v-if="loading" class="py-16 text-center text-sm text-slate-400">Loading project…</section>
    <section v-else-if="error" class="rounded-xl border border-rose-500/40 bg-rose-500/10 p-5 text-rose-200"><p>{{ error }}</p><RouterLink :to="{ name: 'projects' }" class="mt-3 inline-block text-sm font-semibold underline">Back to projects</RouterLink></section>
    <section v-else-if="project"><RouterLink :to="{ name: 'projects' }" class="text-sm text-cyan-300 hover:text-cyan-200">← Projects</RouterLink><div class="mt-5 flex flex-wrap items-start justify-between gap-5"><div><h1 class="text-3xl font-bold">{{ project.name }}</h1><p v-if="project.description" class="mt-2 max-w-2xl text-slate-400">{{ project.description }}</p><p class="mt-3 text-sm text-slate-500">{{ members.length }} {{ members.length === 1 ? 'member' : 'members' }}</p></div><div class="flex flex-wrap gap-2"><button class="rounded-md border border-slate-700 px-3 py-2 text-sm text-slate-200 hover:border-cyan-300" @click="showMembers = true">Manage members</button><button class="rounded-md bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-cyan-200" @click="openCreateTask">New task</button></div></div><div class="mt-8 grid gap-5 lg:grid-cols-3"><section v-for="column in columns" :key="column.status" class="rounded-xl border border-slate-800 bg-slate-900/60 p-4"><div class="mb-4 flex items-center justify-between"><h2 class="font-semibold text-slate-100">{{ column.label }}</h2><span class="rounded bg-slate-800 px-2 py-0.5 text-xs text-slate-400">{{ groupedTasks[column.status].length }}</span></div><div class="space-y-3"><TaskCard v-for="task in groupedTasks[column.status]" :key="task.id" :task="task" :members="members" @select="openTask" /><p v-if="groupedTasks[column.status].length === 0" class="rounded-lg border border-dashed border-slate-700 px-3 py-6 text-center text-xs text-slate-500">No tasks</p></div></section></div><TaskModal v-if="showTask" :task="selectedTask" :members="members" :saving="savingTask" :error="taskError" @close="showTask = false" @save="saveTask" @remove="removeTask" /><MembersModal v-if="showMembers" :members="members" :can-manage="canManageMembers" :saving="savingMember" :error="memberError" @close="showMembers = false" @add="addMember" @remove="removeMember" /></section>
</template>
